---

before_script:
  - eval $(opam config env)
  - ./configure.sh

build:8.10:
  variables:
    COQ: 8.10
  image: coqorg/coq:$COQ
  script:
    - make
    - make bdist VERSION=
    - mv _build/turing.tar.bz2 turing-coq-$COQ.tar.bz2
  artifacts:
    paths: [turing-coq-$COQ.tar.bz2]

build:8.11.0:
  variables:
    COQ: 8.11.0
  image: coqorg/coq:$COQ
  script:
    - make
    - make bdist VERSION=
    - mv _build/turing.tar.bz2 turing-coq-$COQ.tar.bz2
  artifacts:
    paths: [turing-coq-$COQ.tar.bz2]

build:8.10.2:
  variables:
    COQ: 8.10.2
  image: coqorg/coq:$COQ
  script:
    - make
    - make bdist VERSION=
    - mv _build/turing.tar.bz2 turing-coq-$COQ.tar.bz2
  artifacts:
    paths: [turing-coq-$COQ.tar.bz2]
