---

before_script:
  - eval $(opam config env)
  - ./configure.sh

build:8.14.0:
  image: coqorg/coq:8.14
  script:
    - make
    - make bdist VERSION=

build:8.13.2:
  image: coqorg/coq:8.13.2
  script:
    - make
    - make bdist VERSION=

build:8.12.2:
  image: coqorg/coq:8.12.2
  script:
    - make
    - make bdist VERSION=

build:8.11.0:
  image: coqorg/coq:8.11
  script:
    - make
    - make bdist VERSION=

build:8.10.2:
  image: coqorg/coq:8.10.2
  script:
    - make
    - make bdist VERSION=

