---

before_script:
  - eval $(opam config env)
  - ./configure.sh

build:8.10.0:
  image: coqorg/coq:8.10
  script:
    - make
    - make bdist VERSION=
    - mv _build/turing.tar.bz2 turing-coq-8.10.0.tar.bz2
#  artifacts:
#    paths: [turing-coq-8.10.0.tar.bz2]

build:8.11.0:
  image: coqorg/coq:8.11
  script:
    - make
    - make bdist VERSION=
    - mv _build/turing.tar.bz2 turing-coq-8.11.0.tar.bz2
#  artifacts:
#    paths: [turing-coq-8.11.0.tar.bz2]

build:8.10.2:
  image: coqorg/coq:8.10.2
  script:
    - make
    - make bdist VERSION=
    - mv _build/turing.tar.bz2 turing-coq-8.10.2.tar.bz2
#  artifacts:
#    paths: [turing-coq-8.10.2.tar.bz2]
