---

before_script:
  - eval $(opam config env)
  - ./configure.sh

build:8.11.0:
  image: coqorg/coq:8.11.0
  script:
    - make bdist VERSION=-8.11.0
  artifacts:
    paths: [_build/turing-8.11.0.tar.bz2]
