environment:
  scoop: c:\tools\scoop
  coq_version: 2022.04.0
  installer: c:\tools\install-scoop.ps1

init:
  - ps: (Get-PSProvider FileSystem).Home = 'c:\tools\'
  - ps: irm get.scoop.sh -outfile $env:installer
  - ps: $env:installer -RunAsAdmin
  - ps: Remove-Item $env:installer -Force

build_script:
  - ps: dir
  - ps: .\build.ps1

# Install our Scoop script and try to compile our hello world.
# test_script:
#   - ps: scoop install .\scoop\turing.json
#   - ps: coqc .\scoop\Test.v

# - ps: dir "~\scoop\apps\turing\$env:coq_version\"
# - ps: dir "$env:SCOOP\apps\coq\8.11.0\lib\coq\user-contrib\Turing"
#      "script": "Expand-7zipArchive -Overwrite Skip \"$dir\\$fname\" \"$(appdir coq $global)\\current\\lib\\coq\\user-contrib\""

artifacts:
  - path: _build/turing.zip
    name: Turing




