environment:
  scoop: c:\tools\scoop

init:
  - ps: (Get-PSProvider FileSystem).Home = 'c:\tools\'
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install coq@8.11.0

build_script:
  - ps: dir
  - ps: .\build.ps1
  - ps: dir "$env:SCOOP\apps\coq"

artifacts:
  - path: _build/turing.zip
    name: Turing
