environment:
  scoop: c:\tools\scoop

init:
  - ps: (Get-PSProvider FileSystem).Home = 'c:\tools\'
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install coq@8.11.0

build_script:
  - ps: dir
  - ps: .\build.ps1

# Install our Scoop script and try to compile our hello world.
test_script:
  - ps: scoop install .\scoop\turing.json
  - ps: coqc .\scoop\Test.v

# - ps: dir "~\scoop\apps\turing\2020.02.1\"
# - ps: dir "$env:SCOOP\apps\coq\8.11.0\lib\coq\user-contrib\Turing"
#      "script": "Expand-7zipArchive -Overwrite Skip \"$dir\\$fname\" \"$(appdir coq $global)\\current\\lib\\coq\\user-contrib\""

artifacts:
  - path: _build/turing.zip
    name: Turing
