environment:
  scoop: c:\tools\scoop
  coq_version: 2022.04.1
  installer: c:\tools\install-scoop.ps1

init:
  - ps: (Get-PSProvider FileSystem).Home = 'c:\tools\'
  - ps: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
  - ps: scoop install coq@$env:coq_version

build_script:
  - ps: dir
  - ps: .\build.ps1

# Install our Scoop script and try to compile our hello world.
# test_script:
#   - ps: irm "https://gitlab.com/umb-svl/turing/-/jobs/artifacts/main/raw/turing.json?job=win" -outfile turing.json
#   - ps: scoop install turing.json
#   - ps: coqc .\scoop\Test.v


